default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  socket: /tmp/mysql.sock

development:
  adapter: mysql2
  encoding: utf8mb4
  database: kimowota_api_development
  username: root
  password: password
  host: localhost
  port: 3306

test:
  <<: *default
  database: kimowota_api_test

production:
  <<: *default
  database: kimowota_api_production
  username: kimowota_api
  password: <%= ENV['KIMOWOTA_API_DATABASE_PASSWORD'] %>
